# 应用名称
spring:
  application:
    name: boot_mybatis_demo1

  datasource:
    url: jdbc:mysql://localhost:3306/data_config?useUnicode=true;characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

server:
  port: 8017


mybatis:
  mapper-locations: classpath*:mapper/*.xml
