# 应用名称
spring:
  application:
    name: boot_mybatisplus_demo1
  datasource:
    url: jdbc:mysql://localhost:3308/study_demo1?useUnicode=true;characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

server:
  port: 8018

logging:
  level:
    com.study.lx.mybatisplus.mapper: debug


mybatis-plus:
  global-config:
    db-config:
      table-prefix: F_